=begin
#IPGeolocation.io - IP intelligence products

#Ipgeolocation provides a set of APIs to make ip based decisions.

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'cgi'

module IpgeolocationSdk
  class TimezoneApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Timezone information details
    # The Time Zone API provides current time, date, and time zone-related information. It supports various input types including time zone name, geographic coordinates, addresses, IPs, and location codes.  The API determines the time zone based on the following priority order if multiple parameters are provided:   1. Time Zone Name   2. Geographic Coordinates (latitude & longitude)   3. Location Address   4. IP Address   5. IATA Code   6. ICAO Code   7. UN/LOCODE  Enriched response data is returned based on the type of input: - IP: includes geolocation info - Address: includes location metadata - IATA/ICAO: includes airport info - UN/LOCODE: includes city details  You can call the time zone API without passing any time zone, coordinates, IATA, ICAO, LO code or IP address as well. It will use the calling machine's IP address to return the regional time zone information. 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :tz pass a valid time zone name as a query parameter tz to get the time zone information.
    # @option opts [String] :location pass any address of a location as the query parameter location to get the time zone information.
    # @option opts [Float] :lat pass the latitude of a location as query parameters to get the time zone information.
    # @option opts [Float] :long pass the longitude of a location as query parameters to get the time zone information.
    # @option opts [String] :ip You can pass any IPv4 or IPv6 address as a query parameter ip to get the regional timezone information.
    # @option opts [String] :iata_code pass any 3 letter IATA code as a query paramter iata_code to get the comprehensive airport details along with the time zone information, in which that airport exists.
    # @option opts [String] :icao_code pass any 4 letter ICAO code as a query paramter icao_code to get the comprehensive airport details along with the time zone information, in which that airport exists.
    # @option opts [String] :lo_code pass any 5 letter UNLOCODE as a query paramter lo_code to get the comprehensive lo code/city details along with the time zone information of the concerned city.
    # @option opts [String] :output Desired output format (json or xml).
    # @option opts [String] :lang By default, the API responds in English. You can change the response language by passing the language code as a query parameter &#x60;lang&#x60;. Multi language feature is available only for &#x60;paid users&#x60;.
    # @return [TimeZoneDetailedResponse]
    def get_timezone_info(opts = {})
      data, _status_code, _headers = get_timezone_info_with_http_info(opts)
      data
    end

    # Timezone information details
    # The Time Zone API provides current time, date, and time zone-related information. It supports various input types including time zone name, geographic coordinates, addresses, IPs, and location codes.  The API determines the time zone based on the following priority order if multiple parameters are provided:   1. Time Zone Name   2. Geographic Coordinates (latitude &amp; longitude)   3. Location Address   4. IP Address   5. IATA Code   6. ICAO Code   7. UN/LOCODE  Enriched response data is returned based on the type of input: - IP: includes geolocation info - Address: includes location metadata - IATA/ICAO: includes airport info - UN/LOCODE: includes city details  You can call the time zone API without passing any time zone, coordinates, IATA, ICAO, LO code or IP address as well. It will use the calling machine&#39;s IP address to return the regional time zone information. 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :tz pass a valid time zone name as a query parameter tz to get the time zone information.
    # @option opts [String] :location pass any address of a location as the query parameter location to get the time zone information.
    # @option opts [Float] :lat pass the latitude of a location as query parameters to get the time zone information.
    # @option opts [Float] :long pass the longitude of a location as query parameters to get the time zone information.
    # @option opts [String] :ip You can pass any IPv4 or IPv6 address as a query parameter ip to get the regional timezone information.
    # @option opts [String] :iata_code pass any 3 letter IATA code as a query paramter iata_code to get the comprehensive airport details along with the time zone information, in which that airport exists.
    # @option opts [String] :icao_code pass any 4 letter ICAO code as a query paramter icao_code to get the comprehensive airport details along with the time zone information, in which that airport exists.
    # @option opts [String] :lo_code pass any 5 letter UNLOCODE as a query paramter lo_code to get the comprehensive lo code/city details along with the time zone information of the concerned city.
    # @option opts [String] :output Desired output format (json or xml).
    # @option opts [String] :lang By default, the API responds in English. You can change the response language by passing the language code as a query parameter &#x60;lang&#x60;. Multi language feature is available only for &#x60;paid users&#x60;.
    # @return [Array<(TimeZoneDetailedResponse, Integer, Hash)>] TimeZoneDetailedResponse data, response status code and response headers
    def get_timezone_info_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TimezoneApi.get_timezone_info ...'
      end
      allowable_values = ["en", "de", "ru", "ja", "fr", "cn", "es", "cs", "it", "ko", "fa", "pt"]
      if @api_client.config.client_side_validation && opts[:'lang'] && !allowable_values.include?(opts[:'lang'])
        fail ArgumentError, "invalid value for \"lang\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/timezone'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'tz'] = opts[:'tz'] if !opts[:'tz'].nil?
      query_params[:'location'] = opts[:'location'] if !opts[:'location'].nil?
      query_params[:'lat'] = opts[:'lat'] if !opts[:'lat'].nil?
      query_params[:'long'] = opts[:'long'] if !opts[:'long'].nil?
      query_params[:'ip'] = opts[:'ip'] if !opts[:'ip'].nil?
      query_params[:'iata_code'] = opts[:'iata_code'] if !opts[:'iata_code'].nil?
      query_params[:'icao_code'] = opts[:'icao_code'] if !opts[:'icao_code'].nil?
      query_params[:'lo_code'] = opts[:'lo_code'] if !opts[:'lo_code'].nil?
      query_params[:'output'] = opts[:'output'] if !opts[:'output'].nil?
      query_params[:'lang'] = opts[:'lang'] if !opts[:'lang'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json', 'application/xml']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'TimeZoneResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuth']

      new_options = opts.merge(
        :operation => :"TimezoneApi.get_timezone_info",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TimezoneApi#get_timezone_info\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
