=begin
#IPGeolocation.io - IP intelligence products

#Ipgeolocation provides a set of APIs to make ip based decisions.

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for IpgeolocationSdk::SecurityApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SecurityApi' do
  before do
    # run before each test
    @api_instance = IpgeolocationSdk::SecurityApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecurityApi' do
    it 'should create an instance of SecurityApi' do
      expect(@api_instance).to be_instance_of(IpgeolocationSdk::SecurityApi)
    end
  end

  # unit tests for get_bulk_ip_security_info
  # The Bulk IP Security Lookup API can provide security details for up to &#x60;50,000&#x60; bulk IPs. This API also has parameters to customize the response, just like the single IP Security Lookup API.
  # @param get_bulk_ip_geolocation_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :include Include optional objects like &#x60;location&#x60;, &#x60;network&#x60;.  Use comma-separated values. Example: include&#x3D;location,network 
  # @option opts [String] :fields Get specific fields, objects from the response.
  # @option opts [String] :excludes Exclude specific fields, objects from the response.
  # @option opts [String] :output Desired output format.
  # @option opts [String] :lang By default, the API responds in English. You can change the response language by passing the language code as a query parameter &#x60;lang&#x60;. Multi language feature is available only for &#x60;paid users&#x60;.
  # @return [Array<GetBulkIpSecurityInfo200ResponseInner>]
  describe 'get_bulk_ip_security_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_ip_security_info
  # IP Security API provides security details of a given IP. It detects whether the IP is proxy, tor or bot. It also shows the proxy types of the IP (like VPN, PROXY, RELAY etc.) with it&#39;s VPN/proxy service provider making our API powerful VPN checker. It finds the IPs that are involved in spam activities. It also checks whether the IP links to a cloud provider and includes the provider&#39;s name.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :ip query parameter &#39;ip&#39;. If not provided, will be your network IP
  # @option opts [String] :include Include optional details like location and/or network.
  # @option opts [String] :fields Get specific fields, objects from the response.
  # @option opts [String] :excludes Exclude specific fields, objects from the response.
  # @option opts [String] :output Desired output format (json or xml).
  # @option opts [String] :lang By default, the API responds in English. You can change the response language by passing the language code as a query parameter &#x60;lang&#x60;. Multi language feature is available only for &#x60;paid users&#x60;.
  # @return [SecurityAPIResponse]
  describe 'get_ip_security_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
