=begin
#IPGeolocation.io - IP intelligence products

#Ipgeolocation provides a set of APIs to make ip based decisions.

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for IpgeolocationSdk::TimezoneApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TimezoneApi' do
  before do
    # run before each test
    @api_instance = IpgeolocationSdk::TimezoneApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimezoneApi' do
    it 'should create an instance of TimezoneApi' do
      expect(@api_instance).to be_instance_of(IpgeolocationSdk::TimezoneApi)
    end
  end

  # unit tests for get_timezone_info
  # Timezone information details
  # The Time Zone API provides current time, date, and time zone-related information. It supports various input types including time zone name, geographic coordinates, addresses, IPs, and location codes.  The API determines the time zone based on the following priority order if multiple parameters are provided:   1. Time Zone Name   2. Geographic Coordinates (latitude &amp; longitude)   3. Location Address   4. IP Address   5. IATA Code   6. ICAO Code   7. UN/LOCODE  Enriched response data is returned based on the type of input: - IP: includes geolocation info - Address: includes location metadata - IATA/ICAO: includes airport info - UN/LOCODE: includes city details  You can call the time zone API without passing any time zone, coordinates, IATA, ICAO, LO code or IP address as well. It will use the calling machine&#39;s IP address to return the regional time zone information. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tz pass a valid time zone name as a query parameter tz to get the time zone information.
  # @option opts [String] :location pass any address of a location as the query parameter location to get the time zone information.
  # @option opts [Float] :lat pass the latitude of a location as query parameters to get the time zone information.
  # @option opts [Float] :long pass the longitude of a location as query parameters to get the time zone information.
  # @option opts [String] :ip You can pass any IPv4 or IPv6 address as a query parameter ip to get the regional timezone information.
  # @option opts [String] :iata_code pass any 3 letter IATA code as a query paramter iata_code to get the comprehensive airport details along with the time zone information, in which that airport exists.
  # @option opts [String] :icao_code pass any 4 letter ICAO code as a query paramter icao_code to get the comprehensive airport details along with the time zone information, in which that airport exists.
  # @option opts [String] :lo_code pass any 5 letter UNLOCODE as a query paramter lo_code to get the comprehensive lo code/city details along with the time zone information of the concerned city.
  # @option opts [String] :output Desired output format (json or xml).
  # @option opts [String] :lang By default, the API responds in English. You can change the response language by passing the language code as a query parameter &#x60;lang&#x60;. Multi language feature is available only for &#x60;paid users&#x60;.
  # @return [TimeZoneDetailedResponse]
  describe 'get_timezone_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
