=begin
#IPGeolocation.io - IP intelligence products

#Ipgeolocation provides a set of APIs to make ip based decisions.

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for IpgeolocationSdk::TimeConversionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TimeConversionApi' do
  before do
    # run before each test
    @api_instance = IpgeolocationSdk::TimeConversionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimeConversionApi' do
    it 'should create an instance of TimeConversionApi' do
      expect(@api_instance).to be_instance_of(IpgeolocationSdk::TimeConversionApi)
    end
  end

  # unit tests for convert_time_between_timezones
  # You can convert a timestamp provided as a query paramter time from one time zone to another time zone.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :time time parameter takes the input in the following two formats: i) &#39;yyyy-MM-dd HH:mm&#39;, and ii) &#39;yyyy-MM-dd HH:mm:ss&#39;. This parameter is optional and you can omit it to convert the current time between two coordinates, time zones or locations.
  # @option opts [String] :tz_from timezone to convert from
  # @option opts [String] :tz_to timezone to convert to
  # @option opts [Float] :lat_from latitude to convert from
  # @option opts [Float] :long_from longitude to convert from
  # @option opts [Float] :lat_to latitude to convert to
  # @option opts [Float] :long_to longitude to convert to
  # @option opts [String] :location_from location to convert from
  # @option opts [String] :location_to location to convert to
  # @option opts [String] :icao_from location to convert from
  # @option opts [String] :icao_to location to convert to
  # @option opts [String] :iata_from location to convert from
  # @option opts [String] :iata_to location to convert to
  # @option opts [String] :locode_from location to convert from
  # @option opts [String] :locode_to location to convert to
  # @return [TimeConversionResponse]
  describe 'convert_time_between_timezones test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
