=begin
#IPGeolocation.io - IP intelligence products

#Ipgeolocation provides a set of APIs to make ip based decisions.

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IpgeolocationSdk::GetBulkIpSecurityInfo200ResponseInner1
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe IpgeolocationSdk::GetBulkIpSecurityInfo200ResponseInner1 do
  describe '.openapi_one_of' do
    it 'lists the items referenced in the oneOf array' do
      expect(described_class.openapi_one_of).to_not be_empty
    end
  end

  describe '.build' do
    it 'returns the correct model' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
