=begin
#IPGeolocation.io - IP intelligence products

#Ipgeolocation provides a set of APIs to make ip based decisions.

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module IpgeolocationSdk
  class Security
    attr_accessor :threat_score

    attr_accessor :is_tor

    attr_accessor :is_proxy

    attr_accessor :proxy_type

    attr_accessor :proxy_provider

    attr_accessor :is_anonymous

    attr_accessor :is_known_attacker

    attr_accessor :is_spam

    attr_accessor :is_bot

    attr_accessor :is_cloud_provider

    attr_accessor :cloud_provider

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'threat_score' => :'threat_score',
        :'is_tor' => :'is_tor',
        :'is_proxy' => :'is_proxy',
        :'proxy_type' => :'proxy_type',
        :'proxy_provider' => :'proxy_provider',
        :'is_anonymous' => :'is_anonymous',
        :'is_known_attacker' => :'is_known_attacker',
        :'is_spam' => :'is_spam',
        :'is_bot' => :'is_bot',
        :'is_cloud_provider' => :'is_cloud_provider',
        :'cloud_provider' => :'cloud_provider'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'threat_score' => :'Integer',
        :'is_tor' => :'Boolean',
        :'is_proxy' => :'Boolean',
        :'proxy_type' => :'String',
        :'proxy_provider' => :'String',
        :'is_anonymous' => :'Boolean',
        :'is_known_attacker' => :'Boolean',
        :'is_spam' => :'Boolean',
        :'is_bot' => :'Boolean',
        :'is_cloud_provider' => :'Boolean',
        :'cloud_provider' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IpgeolocationSdk::Security` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IpgeolocationSdk::Security`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'threat_score')
        self.threat_score = attributes[:'threat_score']
      end

      if attributes.key?(:'is_tor')
        self.is_tor = attributes[:'is_tor']
      end

      if attributes.key?(:'is_proxy')
        self.is_proxy = attributes[:'is_proxy']
      end

      if attributes.key?(:'proxy_type')
        self.proxy_type = attributes[:'proxy_type']
      end

      if attributes.key?(:'proxy_provider')
        self.proxy_provider = attributes[:'proxy_provider']
      end

      if attributes.key?(:'is_anonymous')
        self.is_anonymous = attributes[:'is_anonymous']
      end

      if attributes.key?(:'is_known_attacker')
        self.is_known_attacker = attributes[:'is_known_attacker']
      end

      if attributes.key?(:'is_spam')
        self.is_spam = attributes[:'is_spam']
      end

      if attributes.key?(:'is_bot')
        self.is_bot = attributes[:'is_bot']
      end

      if attributes.key?(:'is_cloud_provider')
        self.is_cloud_provider = attributes[:'is_cloud_provider']
      end

      if attributes.key?(:'cloud_provider')
        self.cloud_provider = attributes[:'cloud_provider']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          threat_score == o.threat_score &&
          is_tor == o.is_tor &&
          is_proxy == o.is_proxy &&
          proxy_type == o.proxy_type &&
          proxy_provider == o.proxy_provider &&
          is_anonymous == o.is_anonymous &&
          is_known_attacker == o.is_known_attacker &&
          is_spam == o.is_spam &&
          is_bot == o.is_bot &&
          is_cloud_provider == o.is_cloud_provider &&
          cloud_provider == o.cloud_provider
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [threat_score, is_tor, is_proxy, proxy_type, proxy_provider, is_anonymous, is_known_attacker, is_spam, is_bot, is_cloud_provider, cloud_provider].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = IpgeolocationSdk.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
